### ISSUE TITLE
 Build failed 

### ISSUE THREAD

**Issue by ghost** [liho98/moviedb-app#20]
-  Building for production...
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
 ERROR  Failed to compile with 5 errors18:18:08

 error  in ./src/views/Home.vue

Module Error (from ./node_modules/eslint-loader/index.js):
error: 'id' is assigned a value but never used (no-unused-vars) at src\views\Home.vue:167:11:
  165 |     async getMovListDetails(list) {
  166 |       // this.movDetailsList = await list;
> 167 |       let id = await this.$store.state.selectedMovieId;
      |           ^
  168 |       this.title = await list.original_title;
  169 |       this.genres = await list.genres;
  170 |       this.overview = await list.overview;

error: 'id' is assigned a value but never used (no-unused-vars) at src\views\Home.vue:180:11:
  178 |     },
  179 |     async getTvListDetails(list) {
> 180 |       let id = await this.$store.state.selectedMovieId;
      |           ^
  181 |       this.title = await list.name;
  182 |       this.genres = await list.genres;
  183 |       this.overview = await list.overview;

error: 'newId' is defined but never used (no-unused-vars) at src\views\Home.vue:254:21:
  252 |     //   // this.getImage(newList);
  253 |     // },
> 254 |     selectedMovieId(newId, oldId) {
      |                     ^
  255 |       let tab = this.$store.state.selectedTab;
  256 |       // console.log(tab)
  257 |       this.changeTab(tab);

error: 'oldId' is defined but never used (no-unused-vars) at src\views\Home.vue:254:28:
  252 |     //   // this.getImage(newList);
  253 |     // },
> 254 |     selectedMovieId(newId, oldId) {
      |                            ^
  255 |       let tab = this.$store.state.selectedTab;
  256 |       // console.log(tab)
  257 |       this.changeTab(tab);

error: 'OldTab' is defined but never used (no-unused-vars) at src\views\Home.vue:260:25:
  258 |       this.stop();
  259 |     },
> 260 |     selectedTab(newTab, OldTab) {
      |                         ^
  261 |       this.changeTab(newTab);
  262 |       this.stop();
  263 |     },

error: 'newList' is defined but never used (no-unused-vars) at src\views\Home.vue:264:22:
  262 |       this.stop();
  263 |     },
> 264 |     movieDetailsList(newList, oldList) {
      |                      ^
  265 |       this.changeTab("Movie");
  266 |       // console.log("newList")
  267 |     },

error: 'oldList' is defined but never used (no-unused-vars) at src\views\Home.vue:264:31:
  262 |       this.stop();
  263 |     },
> 264 |     movieDetailsList(newList, oldList) {
      |                               ^
  265 |       this.changeTab("Movie");
  266 |       // console.log("newList")
  267 |     },

error: 'newList' is defined but never used (no-unused-vars) at src\views\Home.vue:268:19:
  266 |       // console.log("newList")
  267 |     },
> 268 |     tvDetailsList(newList, oldList) {
      |                   ^
  269 |       this.changeTab("TV Shows");
  270 |       // console.log(newList)
  271 |     }

error: 'oldList' is defined but never used (no-unused-vars) at src\views\Home.vue:268:28:
  266 |       // console.log("newList")
  267 |     },
> 268 |     tvDetailsList(newList, oldList) {
      |                            ^
  269 |       this.changeTab("TV Shows");
  270 |       // console.log(newList)
  271 |     }

9 errors found.

 @ ./src/router/index.js 3:0-37 8:13-17
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./src/components/RightNaviDrawer.vue

Module Error (from ./node_modules/eslint-loader/index.js):
error: 'newList' is defined but never used (no-unused-vars) at src\components\RightNaviDrawer.vue:97:15:
   95 |   },

**Comment by liho98** [comment]
fixed ya, actually u just need to uncomment the lintOnSave from vue.config.js
```
module.exports = {
  "transpileDependencies": [
    "vuetify"
  ],
  lintOnSave: false,
}
```
